# Generated by Django 4.2.5 on 2023-09-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_cover_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tagline',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
